# Generated by Django 4.2.11 on 2026-05-11 19:01

import apps.documents.models
from django.db import migrations, models
import simple_history.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to=apps.documents.models.document_upload_path)),
                ('document_type', models.CharField(choices=[('contract', 'Contrat'), ('receipt', 'Reçu'), ('invoice', 'Facture'), ('report', 'Rapport'), ('id', "Pièce d'identité"), ('other', 'Autre')], default='other', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Actif'), ('archived', 'Archivé'), ('deleted', 'Supprimé')], default='active', max_length=20)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('file_type', models.CharField(blank=True, max_length=50)),
                ('tags', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalDocument',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('file', models.TextField(max_length=100)),
                ('document_type', models.CharField(choices=[('contract', 'Contrat'), ('receipt', 'Reçu'), ('invoice', 'Facture'), ('report', 'Rapport'), ('id', "Pièce d'identité"), ('other', 'Autre')], default='other', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Actif'), ('archived', 'Archivé'), ('deleted', 'Supprimé')], default='active', max_length=20)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('file_type', models.CharField(blank=True, max_length=50)),
                ('tags', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Document',
                'verbose_name_plural': 'historical Documents',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
