# Generated by Django 4.2.11 on 2026-05-12 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_simplify_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('comptable', 'Comptable'), ('membre', 'Membre')], default='membre', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('comptable', 'Comptable'), ('membre', 'Membre')], default='membre', max_length=20),
        ),
    ]
